version: '2'

services:

  # hall-eureka-server

  hall-eureka-server-1:
    build: ./hall-eureka-server
    image: comoyi/hall-eureka-server:0.0.1
    networks:
      - hall
    hostname: hall-eureka-server-1
    ports:
      - 30101:30100
    environment:
      - APP_PROFILES=test,1

  hall-eureka-server-2:
    build: ./hall-eureka-server
    image: comoyi/hall-eureka-server:0.0.1
    networks:
      - hall
    hostname: hall-eureka-server-2
    ports:
      - 30102:30100
    environment:
      - APP_PROFILES=test,2

  hall-eureka-server-3:
    build: ./hall-eureka-server
    image: comoyi/hall-eureka-server:0.0.1
    networks:
      - hall
    hostname: hall-eureka-server-3
    ports:
      - 30103:30100
    environment:
      - APP_PROFILES=test,3

  # hall-api

  hall-api:
    build: ./hall-api
    image: comoyi/hall-api:0.0.1
    networks:
      - hall
    hostname: hall-api
    ports:
      - 30201:30200
    environment:
      - APP_PROFILES=test
    depends_on:
      - hall-eureka-server-1
      - hall-eureka-server-2
      - hall-eureka-server-3

  # hall-admin

  hall-admin:
    build: ./hall-admin
    image: comoyi/hall-admin:0.0.1
    networks:
      - hall
    hostname: hall-admin
    ports:
      - 30301:30300
    environment:
      - APP_PROFILES=test
    depends_on:
      - hall-eureka-server-1
      - hall-eureka-server-2
      - hall-eureka-server-3

  # hall-user

  hall-user:
    build: ./hall-user
    image: comoyi/hall-user:0.0.1
    networks:
      - hall
    hostname: hall-user
    ports:
      - 30501:30500
    environment:
      - APP_PROFILES=test
    depends_on:
      - hall-eureka-server-1
      - hall-eureka-server-2
      - hall-eureka-server-3

networks:
  hall:
    driver: bridge
