server:
  port: 30200

spring:
  application:
    name: hall-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hall-eureka-server-1:30100/eureka,http://hall-eureka-server-2:30100/eureka,http://hall-eureka-server-3:30100/eureka
    instance:
      hostname: hall-api
