server:
  port: 30300

spring:
  application:
    name: hall-admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30100/eureka
    instance:
      hostname: hall-admin
