server:
  port: 30200

spring:
  application:
    name: hall-admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hall-eureka-server:30100/eureka
    instance:
      hostname: hall-admin
