server:
  port: 8091

spring:
  application:
    name: hall-admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hall-eureka-server-1:8070/eureka,http://hall-eureka-server-2:8070/eureka
    instance:
      hostname: hall-admin
