server:
  port: 30500

spring:
  application:
    name: hall-user
  datasource:
    url: jdbc:mysql://127.0.0.1:20101/hall
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30100/eureka
    instance:
      hostname: hall-user
