server:
  port: 8092

spring:
  application:
    name: hall-user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8070/eureka
    instance:
      hostname: 127.0.0.1
