eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hall-eureka-server-2:${server.port}/eureka
    instance:
      hostname: hall-eureka-server-1
