server:
  port: 30100

spring:
  application:
    name: hall-eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    instance:
      hostname: hall-eureka-server
  server:
    enable-self-preservation: false
