eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hall-eureka-server-1:${server.port}/eureka,http://hall-eureka-server-3:${server.port}/eureka
    instance:
      hostname: hall-eureka-server-2
  server:
    enable-self-preservation: false
